/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=../web/wrangler.jsonc --include-runtime=false ../web/worker-configuration.d.ts` (hash: b236b4d58ef2a840546865a63e238e14)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	ACCOUNTS: DurableObjectNamespace<import("../worker/src/index").AccountDurableObject>;
	LOBBY: DurableObjectNamespace<import("../worker/src/index").LobbyDurableObject>;
	GAME_ROOMS: DurableObjectNamespace<import("../worker/src/index").GameRoomDurableObject>;
	RATE_LIMITS: DurableObjectNamespace<import("../worker/src/index").EdgeRateLimitDurableObject>;
	PROGRESSION: DurableObjectNamespace<import("../worker/src/index").ProgressionDurableObject>;
	MATCHMAKING: DurableObjectNamespace<import("../worker/src/index").MatchmakingDurableObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../worker/src/index");
		durableNamespaces: "AccountDurableObject" | "LobbyDurableObject" | "GameRoomDurableObject" | "EdgeRateLimitDurableObject" | "ProgressionDurableObject" | "MatchmakingDurableObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
