/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=../web/wrangler.jsonc --include-runtime=false ../web/worker-configuration.d.ts` (hash: 2d09b9fae556d51b534eb1e56d0e45a1)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	ACCOUNTS: DurableObjectNamespace<import("../worker/src/index").AccountDurableObject>;
	LOBBY: DurableObjectNamespace<import("../worker/src/index").LobbyDurableObject>;
	GAME_ROOMS: DurableObjectNamespace<import("../worker/src/index").GameRoomDurableObject>;
	RATE_LIMITS: DurableObjectNamespace<import("../worker/src/index").EdgeRateLimitDurableObject>;
	PROGRESSION: DurableObjectNamespace<import("../worker/src/index").ProgressionDurableObject>;
	MATCHMAKING: DurableObjectNamespace<import("../worker/src/index").MatchmakingDurableObject>;
	SOCIAL: DurableObjectNamespace<import("../worker/src/index").SocialDurableObject>;
	OPERATIONS: DurableObjectNamespace<import("../worker/src/index").OperationsDurableObject>;
	CONTENT: DurableObjectNamespace<import("../worker/src/index").ContentDurableObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../worker/src/index");
		durableNamespaces: "AccountDurableObject" | "LobbyDurableObject" | "GameRoomDurableObject" | "EdgeRateLimitDurableObject" | "ProgressionDurableObject" | "MatchmakingDurableObject" | "SocialDurableObject" | "OperationsDurableObject" | "ContentDurableObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
