// Generated by the SvelteKit Cloudflare adapter during `npm run build:cloudflare`.
// @ts-expect-error generated JavaScript has no declaration file
import svelteWorker from "../../web/.svelte-kit/cloudflare/_worker.js";
import { AccountDurableObject } from "./objects/account";
import { GameRoomDurableObject } from "./objects/room";
import { LobbyDurableObject } from "./objects/lobby";
import { EdgeRateLimitDurableObject } from "./objects/rate-limit";
import {
  BALANCE,
  DomainError,
  MAX_PROTOCOL_VERSION,
  MIN_PROTOCOL_VERSION,
  PROTOCOL_CAPABILITIES,
  PROTOCOL_VERSION,
  type ErrorCode,
  type PlayerAccount,
  type SessionRecord,
} from "./domain/protocol";
import type { WorkerEnv } from "./env";
import {
  bodyObject,
  cookieValue,
  errorResponse,
  expiredSessionCookie,
  internalRequest,
  json,
  noContent,
  protocolMismatchResponse,
  publicSession,
  randomSecret,
  requireString,
  requireUuid,
  sessionCookie,
  sha256,
  withProtocolHeaders,
} from "./http";

export {
  AccountDurableObject,
  EdgeRateLimitDurableObject,
  GameRoomDurableObject,
  LobbyDurableObject,
};

const SESSION_TTL_SECONDS = 30 * 24 * 60 * 60;
const GLOBAL_OBJECT_ID = "global-v1";

export default {
  async fetch(
    request: Request,
    env: WorkerEnv,
    ctx: ExecutionContext,
  ): Promise<Response> {
    const pathname = new URL(request.url).pathname;
    if (pathname === "/ws") return websocket(request, env);
    if (pathname === "/api" || pathname.startsWith("/api/")) {
      if (!acceptsProtocol(request)) return protocolMismatchResponse();
      try {
        await enforceHttpRateLimits(request, env);
        return withProtocolHeaders(await api(request, env), request);
      } catch (error) {
        return withProtocolHeaders(errorResponse(error), request);
      }
    }
    return svelteWorker.fetch(request, env, ctx);
  },
} satisfies ExportedHandler<WorkerEnv>;

async function api(request: Request, env: WorkerEnv): Promise<Response> {
  const url = new URL(request.url);
  const path = url.pathname.slice("/api".length) || "/";

  if (request.method === "GET" && path === "/protocol") {
    return json({
      protocolVersion: PROTOCOL_VERSION,
      minimumSupportedVersion: MIN_PROTOCOL_VERSION,
      maximumSupportedVersion: MAX_PROTOCOL_VERSION,
      capabilities: PROTOCOL_CAPABILITIES,
      balance: BALANCE,
      serverTime: new Date().toISOString(),
    });
  }
  if (request.method === "GET" && path === "/health") {
    return json({
      status: "ok",
      runtime: "cloudflare-workers",
      serverTime: new Date().toISOString(),
    });
  }
  if (
    request.method === "POST" &&
    (path === "/telemetry/funnel" || path === "/telemetry/performance")
  ) {
    await bodyObject(request);
    return noContent();
  }

  if (request.method === "POST" && path === "/sessions")
    return createSession(request, env);
  if (request.method === "GET" && path === "/sessions/current") {
    return json(publicSession(await authenticate(request, env)));
  }
  if (request.method === "DELETE" && path === "/sessions/current") {
    const token = requireToken(request);
    await authenticate(request, env);
    const revoked = await internalJson<RevokedSession>(
      accounts(env).fetch(
        internalRequest("/sessions/delete", { tokenHash: await sha256(token) }),
      ),
    );
    await disconnectRevokedSession(env, revoked);
    return noContent({ "set-cookie": expiredSessionCookie(request.url) });
  }

  if (request.method === "POST" && path === "/accounts/upgrade") {
    return upgradeAccount(request, env);
  }
  if (request.method === "POST" && path === "/accounts/login") {
    return loginAccount(request, env);
  }
  if (request.method === "GET" && path === "/accounts/sessions") {
    const token = requireToken(request);
    await authenticate(request, env);
    return json(
      await internalJson(
        accounts(env).fetch(
          internalRequest("/accounts/sessions", {
            tokenHash: await sha256(token),
          }),
        ),
      ),
    );
  }
  const revokeMatch =
    request.method === "DELETE"
      ? path.match(/^\/accounts\/sessions\/([^/]+)$/)
      : null;
  if (revokeMatch) {
    const token = requireToken(request);
    await authenticate(request, env);
    const revoked = await internalJson<RevokedSession>(
      accounts(env).fetch(
        internalRequest("/accounts/sessions/revoke", {
          tokenHash: await sha256(token),
          sessionId: requireUuid(decodeURIComponent(revokeMatch[1])),
        }),
      ),
    );
    await disconnectRevokedSession(env, revoked);
    return noContent();
  }

  if (request.method === "GET" && path === "/rooms") {
    const result = await internalJson<{ rooms: unknown[] }>(
      lobby(env).fetch(internalRequest("/rooms")),
    );
    return json({
      ...result,
      protocolVersion: PROTOCOL_VERSION,
      serverTime: new Date().toISOString(),
    });
  }
  if (request.method === "POST" && path === "/rooms")
    return createRoomRoute(request, env);
  if (request.method === "POST" && path === "/rooms/join")
    return joinRoomRoute(request, env);

  const roomMatch = path.match(/^\/rooms\/([^/]+)$/);
  if (request.method === "GET" && roomMatch) {
    const session = await authenticate(request, env);
    return proxyRoomSnapshot(
      env,
      requireUuid(decodeURIComponent(roomMatch[1])),
      session,
    );
  }
  const leaveMatch =
    request.method === "POST" ? path.match(/^\/rooms\/([^/]+)\/leave$/) : null;
  if (leaveMatch) {
    const token = requireToken(request);
    const session = await authenticate(request, env);
    const roomId = requireUuid(decodeURIComponent(leaveMatch[1]));
    await internalJson(
      room(env, roomId).fetch(
        internalRequest("/leave", {
          sessionId: session.id,
          now: new Date().toISOString(),
        }),
      ),
      204,
    );
    await updateSessionRoom(env, token, null);
    return noContent();
  }

  if (request.method === "GET" && path === "/games/recover") {
    const session = await authenticate(request, env);
    if (!session.currentRoomId) return json(null);
    return proxyRoomSnapshot(env, session.currentRoomId, session);
  }
  if (request.method === "GET" && path === "/games/spectatable") {
    await authenticate(request, env);
    return json(
      await internalJson(
        lobby(env).fetch(internalRequest("/rooms/spectatable")),
      ),
    );
  }
  const spectateMatch =
    request.method === "GET"
      ? path.match(/^\/games\/([^/]+)\/spectate$/)
      : null;
  if (spectateMatch) {
    await authenticate(request, env);
    return json(
      await internalJson(
        room(env, requireUuid(decodeURIComponent(spectateMatch[1]))).fetch(
          internalRequest("/spectate", { now: new Date().toISOString() }),
        ),
      ),
    );
  }
  const replayMatch =
    request.method === "GET" ? path.match(/^\/games\/([^/]+)\/replay$/) : null;
  if (replayMatch) {
    const session = await authenticate(request, env);
    return json(
      await internalJson(
        room(env, requireUuid(decodeURIComponent(replayMatch[1]))).fetch(
          internalRequest("/replay", { sessionId: session.id }),
        ),
      ),
    );
  }

  return json(
    {
      code: "NOT_FOUND",
      message: "이 Cloudflare 런타임에서 제공하지 않는 API입니다.",
    },
    404,
  );
}

async function createSession(
  request: Request,
  env: WorkerEnv,
): Promise<Response> {
  const body = await bodyObject(request);
  const nickname = requireString(body.nickname).trim();
  if (!/^[\p{L}\p{N} _-]{2,16}$/u.test(nickname))
    throw new DomainError("INVALID_NICKNAME");
  const now = new Date();
  const token = randomSecret();
  const session: SessionRecord = {
    id: crypto.randomUUID(),
    accountId: null,
    nickname,
    tokenHash: await sha256(token),
    createdAt: now.toISOString(),
    lastSeenAt: now.toISOString(),
    currentRoomId: null,
    expiresAt: new Date(
      now.getTime() + SESSION_TTL_SECONDS * 1000,
    ).toISOString(),
  };
  const stored = await internalJson<SessionRecord>(
    accounts(env).fetch(
      internalRequest("/sessions/create", {
        sessionId: session.id,
        accountId: session.accountId,
        nickname: session.nickname,
        tokenHash: session.tokenHash,
        createdAt: session.createdAt,
        lastSeenAt: session.lastSeenAt,
        currentRoomId: session.currentRoomId,
        expiresAt: session.expiresAt,
      }),
    ),
    201,
  );
  return json(publicSession(stored), 201, {
    "set-cookie": sessionCookie(token, request.url, SESSION_TTL_SECONDS),
  });
}

async function upgradeAccount(
  request: Request,
  env: WorkerEnv,
): Promise<Response> {
  const token = requireToken(request);
  const session = await authenticate(request, env);
  if (session.accountId) throw new DomainError("INVALID_STATE");
  const body = await bodyObject(request);
  const handle = requireString(body.handle).trim();
  if (!/^[\p{L}\p{N}_-]{2,16}$/u.test(handle))
    throw new DomainError("INVALID_NICKNAME");
  const recoveryKey = randomSecret();
  const nextToken = randomSecret();
  const result = await internalJson<{
    account: PlayerAccount;
    session: SessionRecord;
  }>(
    accounts(env).fetch(
      internalRequest("/accounts/upgrade", {
        tokenHash: await sha256(token),
        nextTokenHash: await sha256(nextToken),
        handle,
        accountId: crypto.randomUUID(),
        recoveryKeyHash: await sha256(recoveryKey),
        now: new Date().toISOString(),
      }),
    ),
  );
  return json(
    {
      account: {
        id: result.account.id,
        handle: result.account.handle,
        createdAt: result.account.createdAt,
      },
      recoveryKey,
    },
    200,
    {
      "set-cookie": sessionCookie(nextToken, request.url, SESSION_TTL_SECONDS),
    },
  );
}

async function loginAccount(
  request: Request,
  env: WorkerEnv,
): Promise<Response> {
  const body = await bodyObject(request);
  const now = new Date();
  const token = randomSecret();
  const session = await internalJson<SessionRecord>(
    accounts(env).fetch(
      internalRequest("/accounts/login", {
        accountId: requireUuid(body.accountId),
        recoveryKeyHash: await sha256(requireString(body.recoveryKey)),
        sessionId: crypto.randomUUID(),
        nickname: "account",
        tokenHash: await sha256(token),
        createdAt: now.toISOString(),
        lastSeenAt: now.toISOString(),
        currentRoomId: null,
        expiresAt: new Date(
          now.getTime() + SESSION_TTL_SECONDS * 1000,
        ).toISOString(),
      }),
    ),
    201,
  );
  return json(publicSession(session), 201, {
    "set-cookie": sessionCookie(token, request.url, SESSION_TTL_SECONDS),
  });
}

async function createRoomRoute(
  request: Request,
  env: WorkerEnv,
): Promise<Response> {
  const token = requireToken(request);
  const session = await authenticate(request, env);
  if (session.currentRoomId) throw new DomainError("ALREADY_JOINED");
  const body = await bodyObject(request);
  const roomId = crypto.randomUUID();
  let code = "";
  let result: { snapshot: unknown } | null = null;
  for (let attempt = 0; attempt < 5 && !result; attempt += 1) {
    code = inviteCode();
    try {
      result = await internalJson<{ snapshot: unknown }>(
        room(env, roomId).fetch(
          internalRequest("/create", {
            roomId,
            code,
            name: requireString(body.name),
            visibility: body.visibility,
            rules: body.rules,
            session,
            playerId: crypto.randomUUID(),
            now: new Date().toISOString(),
          }),
        ),
        201,
      );
    } catch (error) {
      if (!(error instanceof DomainError) || error.code !== "INVALID_STATE")
        throw error;
    }
  }
  if (!result) throw new DomainError("INTERNAL_ERROR");
  await updateSessionRoom(env, token, roomId);
  return json(
    {
      snapshot: result.snapshot,
      inviteUrl: new URL(`/join/${code}`, request.url).href,
    },
    201,
  );
}

async function joinRoomRoute(
  request: Request,
  env: WorkerEnv,
): Promise<Response> {
  const token = requireToken(request);
  const session = await authenticate(request, env);
  if (session.currentRoomId) throw new DomainError("ALREADY_JOINED");
  const body = await bodyObject(request);
  const lookup = await internalJson<{ roomId: string }>(
    lobby(env).fetch(
      internalRequest("/rooms/lookup", { code: requireString(body.code) }),
    ),
  );
  const result = await internalJson<{ snapshot: unknown }>(
    room(env, lookup.roomId).fetch(
      internalRequest("/join", {
        session,
        playerId: crypto.randomUUID(),
        now: new Date().toISOString(),
      }),
    ),
  );
  await updateSessionRoom(env, token, lookup.roomId);
  return json(result.snapshot);
}

async function websocket(request: Request, env: WorkerEnv): Promise<Response> {
  try {
    if (request.headers.get("upgrade")?.toLowerCase() !== "websocket") {
      return json({ code: "UPGRADE_REQUIRED" }, 426);
    }
    const url = new URL(request.url);
    await enforceRateLimit(request, env, "websocket", 60, 60_000);
    const origin = request.headers.get("origin");
    if (origin && origin !== url.origin) throw new DomainError("UNAUTHORIZED");
    const session = await authenticate(request, env);
    if (!session.currentRoomId) throw new DomainError("NOT_ROOM_MEMBER");
    const headers = new Headers(request.headers);
    headers.set("x-mk01-session-id", session.id);
    return room(env, session.currentRoomId).fetch(
      new Request("https://internal.mk01/websocket", {
        method: "GET",
        headers,
      }),
    );
  } catch (error) {
    return errorResponse(error);
  }
}

async function enforceHttpRateLimits(
  request: Request,
  env: WorkerEnv,
): Promise<void> {
  const pathname = new URL(request.url).pathname;
  const checks = [enforceRateLimit(request, env, "http-ip", 600, 60_000)];
  const token = cookieValue(request);
  if (token)
    checks.push(
      enforceRateLimit(request, env, "http-session", 240, 60_000, token),
    );
  if (request.method === "POST" && pathname === "/api/sessions") {
    checks.push(enforceRateLimit(request, env, "session-create", 20, 60_000));
  }
  await Promise.all(checks);
}

async function enforceRateLimit(
  request: Request,
  env: WorkerEnv,
  category: string,
  limit: number,
  windowMs: number,
  identity?: string,
): Promise<void> {
  const client =
    identity ??
    request.headers.get("cf-connecting-ip") ??
    request.headers.get("x-real-ip") ??
    "local-client";
  const key = await sha256(`${category}:${client}`);
  const limiter = env.RATE_LIMITS.get(env.RATE_LIMITS.idFromName(key));
  await internalJson(
    limiter.fetch(
      internalRequest("/check", { limit, windowMs, now: Date.now() }),
    ),
    204,
  );
}

async function authenticate(
  request: Request,
  env: WorkerEnv,
): Promise<SessionRecord> {
  const token = requireToken(request);
  return internalJson<SessionRecord>(
    accounts(env).fetch(
      internalRequest("/sessions/authenticate", {
        tokenHash: await sha256(token),
        now: new Date().toISOString(),
      }),
    ),
  );
}

async function updateSessionRoom(
  env: WorkerEnv,
  token: string,
  roomId: string | null,
): Promise<void> {
  await internalJson(
    accounts(env).fetch(
      internalRequest("/sessions/room", {
        tokenHash: await sha256(token),
        roomId,
      }),
    ),
    204,
  );
}

interface RevokedSession {
  sessionId: string;
  roomId: string | null;
}

async function disconnectRevokedSession(
  env: WorkerEnv,
  revoked: RevokedSession,
): Promise<void> {
  if (!revoked.roomId) return;
  await internalJson(
    room(env, revoked.roomId).fetch(
      internalRequest("/disconnect-session", {
        sessionId: revoked.sessionId,
        now: new Date().toISOString(),
      }),
    ),
    204,
  );
}

async function proxyRoomSnapshot(
  env: WorkerEnv,
  roomId: string,
  session: SessionRecord,
): Promise<Response> {
  return json(
    await internalJson(
      room(env, roomId).fetch(
        internalRequest("/snapshot", {
          sessionId: session.id,
          now: new Date().toISOString(),
        }),
      ),
    ),
  );
}

function acceptsProtocol(request: Request): boolean {
  const value = request.headers.get("x-mk01-protocol-version");
  if (value === null) return true;
  const version = Number(value);
  return (
    Number.isInteger(version) &&
    version >= MIN_PROTOCOL_VERSION &&
    version <= MAX_PROTOCOL_VERSION
  );
}

function requireToken(request: Request): string {
  const token = cookieValue(request);
  if (!token) throw new DomainError("UNAUTHORIZED");
  return token;
}

function accounts(env: WorkerEnv) {
  return env.ACCOUNTS.get(env.ACCOUNTS.idFromName(GLOBAL_OBJECT_ID));
}

function lobby(env: WorkerEnv) {
  return env.LOBBY.get(env.LOBBY.idFromName(GLOBAL_OBJECT_ID));
}

function room(env: WorkerEnv, roomId: string) {
  return env.GAME_ROOMS.get(env.GAME_ROOMS.idFromName(roomId));
}

async function internalJson<T = unknown>(
  responsePromise: Promise<Response>,
  expectedStatus = 200,
): Promise<T> {
  const response = await responsePromise;
  if (response.status !== expectedStatus) {
    const payload = (await response.json().catch(() => null)) as {
      code?: string;
    } | null;
    if (payload?.code) throw new DomainError(payload.code as ErrorCode);
    throw new DomainError("INTERNAL_ERROR");
  }
  if (response.status === 204) return undefined as T;
  return (await response.json()) as T;
}

function inviteCode(): string {
  const alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  const bytes = crypto.getRandomValues(new Uint8Array(6));
  return [...bytes].map((byte) => alphabet[byte % alphabet.length]).join("");
}
