// Generated by the SvelteKit Cloudflare adapter during `npm run build:cloudflare`.
// @ts-expect-error generated JavaScript has no declaration file
import svelteWorker from "../../web/.svelte-kit/cloudflare/_worker.js";
import { AccountDurableObject } from "./objects/account";
import { GameRoomDurableObject } from "./objects/room";
import { LobbyDurableObject } from "./objects/lobby";
import { EdgeRateLimitDurableObject } from "./objects/rate-limit";
import { ProgressionDurableObject } from "./objects/progression";
import { MatchmakingDurableObject } from "./objects/matchmaking";
import { SocialDurableObject } from "./objects/social";
import { OperationsDurableObject } from "./objects/operations";
import { ContentDurableObject } from "./objects/content";
import {
  BALANCE,
  DomainError,
  MAX_PROTOCOL_VERSION,
  MIN_PROTOCOL_VERSION,
  PROTOCOL_CAPABILITIES,
  PROTOCOL_VERSION,
  type ErrorCode,
  type PlayerAccount,
  type SessionRecord,
} from "./domain/protocol";
import type { WorkerEnv } from "./env";
import {
  bodyObject,
  cookieValue,
  errorResponse,
  expiredSessionCookie,
  internalRequest,
  json,
  noContent,
  protocolMismatchResponse,
  publicSession,
  randomSecret,
  requireString,
  requireUuid,
  sessionCookie,
  sha256,
  withProtocolHeaders,
} from "./http";

export {
  AccountDurableObject,
  EdgeRateLimitDurableObject,
  GameRoomDurableObject,
  LobbyDurableObject,
  ProgressionDurableObject,
  MatchmakingDurableObject,
  SocialDurableObject,
  OperationsDurableObject,
  ContentDurableObject,
};

const SESSION_TTL_SECONDS = 30 * 24 * 60 * 60;
const GLOBAL_OBJECT_ID = "global-v1";

export default {
  async fetch(
    request: Request,
    env: WorkerEnv,
    ctx: ExecutionContext,
  ): Promise<Response> {
    const pathname = new URL(request.url).pathname;
    if (pathname === "/ws") return websocket(request, env);
    if (pathname === "/api" || pathname.startsWith("/api/")) {
      if (!acceptsProtocol(request)) return protocolMismatchResponse();
      try {
        await enforceHttpRateLimits(request, env);
        return withProtocolHeaders(await api(request, env), request);
      } catch (error) {
        return withProtocolHeaders(errorResponse(error), request);
      }
    }
    return svelteWorker.fetch(request, env, ctx);
  },
} satisfies ExportedHandler<WorkerEnv>;

async function api(request: Request, env: WorkerEnv): Promise<Response> {
  const url = new URL(request.url);
  const path = url.pathname.slice("/api".length) || "/";

  if (request.method === "GET" && path === "/protocol") {
    return json({
      protocolVersion: PROTOCOL_VERSION,
      minimumSupportedVersion: MIN_PROTOCOL_VERSION,
      maximumSupportedVersion: MAX_PROTOCOL_VERSION,
      capabilities: PROTOCOL_CAPABILITIES,
      balance: BALANCE,
      serverTime: new Date().toISOString(),
    });
  }
  if (request.method === "GET" && path === "/health") {
    return json({
      status: "ok",
      storage: "durable-objects-sqlite",
      runtime: "cloudflare-workers",
      serverTime: new Date().toISOString(),
      protocolVersion: PROTOCOL_VERSION,
    });
  }
  if (request.method === "GET" && path === "/ready") {
    const now = new Date().toISOString();
    const probes = await Promise.all([
      accounts(env).fetch(internalRequest("/health")),
      lobby(env).fetch(internalRequest("/rooms")),
      matchmaking(env).fetch(internalRequest("/stats")),
      operations(env).fetch(internalRequest("/health")),
      content(env).fetch(internalRequest("/live", { now })),
    ]);
    if (probes.some((response) => !response.ok))
      throw new DomainError("INTERNAL_ERROR");
    return json({
      status: "ready",
      storage: "durable-objects-sqlite",
      runtime: "cloudflare-workers",
      serverTime: now,
      protocolVersion: PROTOCOL_VERSION,
    });
  }
  if (request.method === "GET" && path === "/metrics") {
    const [operationsResponse, queue] = await Promise.all([
      operations(env).fetch(internalRequest("/metrics")),
      internalJson<{
        queued: number;
        rankedQueued: number;
        oldestWaitSeconds: number;
      }>(matchmaking(env).fetch(internalRequest("/stats"))),
    ]);
    if (!operationsResponse.ok) throw new DomainError("INTERNAL_ERROR");
    const persisted = await operationsResponse.text();
    const metrics =
      persisted +
      "# HELP mk01_matchmaking_queue_depth Current durable matchmaking queue entries.\n" +
      "# TYPE mk01_matchmaking_queue_depth gauge\n" +
      `mk01_matchmaking_queue_depth ${queue.queued}\n` +
      "# HELP mk01_ranked_matchmaking_queue_depth Current durable ranked matchmaking queue entries.\n" +
      "# TYPE mk01_ranked_matchmaking_queue_depth gauge\n" +
      `mk01_ranked_matchmaking_queue_depth ${queue.rankedQueued}\n` +
      "# HELP mk01_matchmaking_oldest_age_seconds Age of the oldest durable matchmaking queue entry in seconds.\n" +
      "# TYPE mk01_matchmaking_oldest_age_seconds gauge\n" +
      `mk01_matchmaking_oldest_age_seconds ${queue.oldestWaitSeconds}\n`;
    return new Response(metrics, {
      headers: { "content-type": "text/plain; version=0.0.4" },
    });
  }
  if (
    request.method === "POST" &&
    (path === "/telemetry/funnel" || path === "/telemetry/performance")
  ) {
    await internalJson(
      operations(env).fetch(internalRequest(path, await bodyObject(request))),
      204,
    );
    return noContent();
  }

  if (request.method === "POST" && path === "/sessions")
    return createSession(request, env);
  if (request.method === "GET" && path === "/sessions/current") {
    return json(publicSession(await authenticate(request, env)));
  }
  if (request.method === "DELETE" && path === "/sessions/current") {
    const token = requireToken(request);
    await authenticate(request, env);
    const revoked = await internalJson<RevokedSession>(
      accounts(env).fetch(
        internalRequest("/sessions/delete", { tokenHash: await sha256(token) }),
      ),
    );
    await disconnectRevokedSession(env, revoked);
    return noContent({ "set-cookie": expiredSessionCookie(request.url) });
  }

  if (request.method === "POST" && path === "/accounts/upgrade") {
    return upgradeAccount(request, env);
  }
  if (request.method === "POST" && path === "/accounts/login") {
    return loginAccount(request, env);
  }
  if (request.method === "GET" && path === "/profile") {
    const session = await authenticate(request, env);
    const liveContent = await liveContentRuntime(env, new Date().toISOString());
    return json(
      await internalJson(
        progression(env).fetch(
          internalRequest("/profile", {
            identityId: session.accountId ?? session.id,
            accountId: session.accountId,
            handle: session.nickname,
            now: new Date().toISOString(),
            liveContent: liveContent.view,
            tuning: liveContent.tuning,
          }),
        ),
      ),
    );
  }
  if (request.method === "GET" && path === "/content/live") {
    return json(
      await internalJson(
        content(env).fetch(
          internalRequest("/live", { now: new Date().toISOString() }),
        ),
      ),
    );
  }
  if (request.method === "GET" && path === "/leaderboards/ranked") {
    const session = await authenticate(request, env);
    if (!session.accountId) throw new DomainError("RANKED_ACCOUNT_REQUIRED");
    const limitValue = url.searchParams.get("limit");
    const seasons = await internalJson<{
      currentSeasonId: string;
      seasons: Array<{ seasonId: string; archived: boolean }>;
    }>(
      content(env).fetch(
        internalRequest("/seasons", { now: new Date().toISOString() }),
      ),
    );
    return json(
      await internalJson(
        progression(env).fetch(
          internalRequest("/ranked/leaderboard", {
            accountId: session.accountId,
            seasonId:
              url.searchParams.get("seasonId") ?? seasons.currentSeasonId,
            availableSeasons: seasons.seasons,
            cursor: url.searchParams.get("cursor"),
            limit: limitValue === null ? 20 : Number(limitValue),
            now: new Date().toISOString(),
          }),
        ),
      ),
    );
  }
  if (request.method === "PUT" && path === "/profile/leaderboard-visibility") {
    const session = await authenticate(request, env);
    if (!session.accountId) throw new DomainError("RANKED_ACCOUNT_REQUIRED");
    const body = await bodyObject(request);
    return json(
      await internalJson(
        progression(env).fetch(
          internalRequest("/ranked/visibility", {
            accountId: session.accountId,
            visible: body.visible,
          }),
        ),
      ),
    );
  }
  const missionMatch =
    request.method === "POST"
      ? path.match(/^\/profile\/missions\/([^/]+)\/claim$/)
      : null;
  if (missionMatch) {
    const session = await authenticate(request, env);
    if (!session.accountId) throw new DomainError("UNAUTHORIZED");
    const liveContent = await liveContentRuntime(env, new Date().toISOString());
    return json(
      await internalJson(
        progression(env).fetch(
          internalRequest("/missions/claim", {
            identityId: session.accountId,
            accountId: session.accountId,
            handle: session.nickname,
            missionId: decodeURIComponent(missionMatch[1]),
            now: new Date().toISOString(),
            liveContent: liveContent.view,
            tuning: liveContent.tuning,
          }),
        ),
      ),
    );
  }
  if (request.method === "GET" && path === "/accounts/export") {
    const token = requireToken(request);
    const session = await authenticate(request, env);
    if (!session.accountId) throw new DomainError("UNAUTHORIZED");
    return json(
      await internalJson(
        accounts(env).fetch(
          internalRequest("/accounts/export", {
            tokenHash: await sha256(token),
            requestId: crypto.randomUUID(),
            generatedAt: new Date().toISOString(),
          }),
        ),
      ),
    );
  }
  if (request.method === "DELETE" && path === "/accounts") {
    const token = requireToken(request);
    const session = await authenticate(request, env);
    if (!session.accountId) throw new DomainError("UNAUTHORIZED");
    const body = await bodyObject(request);
    const recoveryKey = requireString(body.recoveryKey);
    if (!/^[A-Za-z0-9_-]{43}$/.test(recoveryKey))
      throw new DomainError("INVALID_REQUEST");
    const result = await internalJson(
      accounts(env).fetch(
        internalRequest("/accounts/delete", {
          tokenHash: await sha256(token),
          recoveryKeyHash: await sha256(recoveryKey),
          confirmation: body.confirmation,
          requestId: crypto.randomUUID(),
          deletedAt: new Date().toISOString(),
        }),
      ),
    );
    return json(result, 200, {
      "set-cookie": expiredSessionCookie(request.url),
    });
  }
  if (request.method === "GET" && path === "/accounts/sessions") {
    const token = requireToken(request);
    await authenticate(request, env);
    return json(
      await internalJson(
        accounts(env).fetch(
          internalRequest("/accounts/sessions", {
            tokenHash: await sha256(token),
          }),
        ),
      ),
    );
  }
  const revokeMatch =
    request.method === "DELETE"
      ? path.match(/^\/accounts\/sessions\/([^/]+)$/)
      : null;
  if (revokeMatch) {
    const token = requireToken(request);
    await authenticate(request, env);
    const revoked = await internalJson<RevokedSession>(
      accounts(env).fetch(
        internalRequest("/accounts/sessions/revoke", {
          tokenHash: await sha256(token),
          sessionId: requireUuid(decodeURIComponent(revokeMatch[1])),
        }),
      ),
    );
    await disconnectRevokedSession(env, revoked);
    return noContent();
  }

  if (request.method === "GET" && path === "/rooms") {
    const result = await internalJson<{ rooms: unknown[] }>(
      lobby(env).fetch(internalRequest("/rooms")),
    );
    return json({
      ...result,
      protocolVersion: PROTOCOL_VERSION,
      serverTime: new Date().toISOString(),
    });
  }
  if (request.method === "POST" && path === "/rooms")
    return createRoomRoute(request, env);
  if (request.method === "POST" && path === "/practice")
    return createPracticeRoute(request, env);
  if (request.method === "POST" && path === "/rooms/join")
    return joinRoomRoute(request, env);

  const roomMatch = path.match(/^\/rooms\/([^/]+)$/);
  if (request.method === "GET" && roomMatch) {
    const session = await authenticate(request, env);
    return proxyRoomSnapshot(
      env,
      requireUuid(decodeURIComponent(roomMatch[1])),
      session,
    );
  }
  const leaveMatch =
    request.method === "POST" ? path.match(/^\/rooms\/([^/]+)\/leave$/) : null;
  if (leaveMatch) {
    const token = requireToken(request);
    const session = await authenticate(request, env);
    const roomId = requireUuid(decodeURIComponent(leaveMatch[1]));
    await internalJson(
      room(env, roomId).fetch(
        internalRequest("/leave", {
          sessionId: session.id,
          now: new Date().toISOString(),
        }),
      ),
      204,
    );
    await updateSessionRoom(env, token, null);
    return noContent();
  }

  if (request.method === "GET" && path === "/games/recover") {
    const session = await authenticate(request, env);
    if (!session.currentRoomId) return json(null);
    return proxyRoomSnapshot(env, session.currentRoomId, session);
  }
  if (request.method === "GET" && path === "/games/history") {
    const session = await authenticate(request, env);
    return json(
      await internalJson(
        progression(env).fetch(
          internalRequest("/history", {
            identityId: session.accountId ?? session.id,
          }),
        ),
      ),
    );
  }
  if (request.method === "GET" && path === "/games/spectatable") {
    await authenticate(request, env);
    return json(
      await internalJson(
        lobby(env).fetch(internalRequest("/rooms/spectatable")),
      ),
    );
  }
  const spectateMatch =
    request.method === "GET"
      ? path.match(/^\/games\/([^/]+)\/spectate$/)
      : null;
  if (spectateMatch) {
    await authenticate(request, env);
    return json(
      await internalJson(
        room(env, requireUuid(decodeURIComponent(spectateMatch[1]))).fetch(
          internalRequest("/spectate", { now: new Date().toISOString() }),
        ),
      ),
    );
  }
  const replayMatch =
    request.method === "GET" ? path.match(/^\/games\/([^/]+)\/replay$/) : null;
  if (replayMatch) {
    const session = await authenticate(request, env);
    return json(
      await internalJson(
        room(env, requireUuid(decodeURIComponent(replayMatch[1]))).fetch(
          internalRequest("/replay", { sessionId: session.id }),
        ),
      ),
    );
  }

  if (request.method === "POST" && path === "/matchmaking") {
    return enqueueMatchmaking(request, env, false);
  }
  if (request.method === "POST" && path === "/matchmaking/ranked") {
    return enqueueMatchmaking(request, env, true);
  }
  if (request.method === "DELETE" && path === "/matchmaking") {
    const session = await authenticate(request, env);
    await internalJson(
      matchmaking(env).fetch(
        internalRequest("/cancel", { sessionId: session.id }),
      ),
      204,
    );
    return noContent();
  }
  if (request.method === "GET" && path === "/social/relationships") {
    const session = await authenticate(request, env);
    return json(
      await internalJson(
        social(env).fetch(
          internalRequest("/relationships", {
            identityId: session.accountId ?? session.id,
            now: new Date().toISOString(),
          }),
        ),
      ),
    );
  }
  if (request.method === "GET" && path === "/social/overview") {
    const session = await authenticate(request, env);
    if (!session.accountId) throw new DomainError("SOCIAL_ACCOUNT_REQUIRED");
    return json(
      await internalJson(
        social(env).fetch(
          internalRequest("/overview", {
            accountId: session.accountId,
            now: new Date().toISOString(),
          }),
        ),
      ),
    );
  }
  if (request.method === "PUT" && path === "/social/privacy") {
    const session = await authenticate(request, env);
    if (!session.accountId) throw new DomainError("SOCIAL_ACCOUNT_REQUIRED");
    const body = await bodyObject(request);
    return json(
      await internalJson(
        social(env).fetch(
          internalRequest("/privacy", {
            accountId: session.accountId,
            allowFriendRequests: body.allowFriendRequests,
            showPresence: body.showPresence,
            allowGameInvites: body.allowGameInvites,
            now: new Date().toISOString(),
          }),
        ),
      ),
    );
  }
  if (request.method === "POST" && path === "/social/actions") {
    return applySocialAction(request, env);
  }
  if (request.method === "POST" && path === "/social/relationships") {
    return updateSocialRelationship(request, env);
  }
  if (request.method === "POST" && path === "/reports") {
    return reportPlayer(request, env);
  }
  if (request.method === "GET" && path === "/admin/moderation/reports") {
    authorizeOperator(request, env, false);
    return json(
      await internalJson(
        operations(env).fetch(
          internalRequest("/reports/list", {
            status: url.searchParams.get("status"),
            search: url.searchParams.get("search"),
            before: url.searchParams.get("before"),
            limit: url.searchParams.get("limit"),
          }),
        ),
      ),
    );
  }
  if (request.method === "GET" && path === "/admin/integrity/signals") {
    authorizeOperator(request, env, false);
    return json(
      await internalJson(
        operations(env).fetch(
          internalRequest("/integrity/list", {
            kind: url.searchParams.get("kind"),
            search: url.searchParams.get("search"),
            before: url.searchParams.get("before"),
            limit: url.searchParams.get("limit"),
          }),
        ),
      ),
    );
  }
  const moderationActionMatch =
    request.method === "POST"
      ? path.match(/^\/admin\/moderation\/reports\/([^/]+)\/actions$/)
      : null;
  if (moderationActionMatch) {
    return moderateReport(
      request,
      env,
      requireUuid(decodeURIComponent(moderationActionMatch[1])),
    );
  }
  if (request.method === "GET" && path === "/admin/support/accounts") {
    authorizeOperator(request, env, false);
    return supportAccount(env, url.searchParams.get("query"));
  }
  const supportRevokeMatch =
    request.method === "POST"
      ? path.match(/^\/admin\/support\/accounts\/([^/]+)\/sessions\/revoke$/)
      : null;
  if (supportRevokeMatch) {
    return revokeSupportSessions(
      request,
      env,
      requireUuid(decodeURIComponent(supportRevokeMatch[1])),
    );
  }
  if (request.method === "GET" && path === "/admin/content/revisions") {
    authorizeOperator(request, env, false);
    const limit = url.searchParams.get("limit");
    return json(
      await internalJson(
        content(env).fetch(
          internalRequest("/history", {
            limit: limit === null ? 25 : Number(limit),
          }),
        ),
      ),
    );
  }
  if (request.method === "POST" && path === "/admin/content/validate") {
    return mutateLiveContent(request, env, "/validate", 200);
  }
  if (request.method === "POST" && path === "/admin/content/revisions") {
    return mutateLiveContent(request, env, "/publish", 201);
  }
  if (request.method === "POST" && path === "/admin/content/rollback") {
    return mutateLiveContent(request, env, "/rollback", 200);
  }

  return json(
    {
      code: "NOT_FOUND",
      message: "이 Cloudflare 런타임에서 제공하지 않는 API입니다.",
    },
    404,
  );
}

async function createSession(
  request: Request,
  env: WorkerEnv,
): Promise<Response> {
  const body = await bodyObject(request);
  const nickname = requireString(body.nickname).trim();
  if (!/^[\p{L}\p{N} _-]{2,16}$/u.test(nickname))
    throw new DomainError("INVALID_NICKNAME");
  const now = new Date();
  const token = randomSecret();
  const session: SessionRecord = {
    id: crypto.randomUUID(),
    accountId: null,
    nickname,
    tokenHash: await sha256(token),
    createdAt: now.toISOString(),
    lastSeenAt: now.toISOString(),
    currentRoomId: null,
    expiresAt: new Date(
      now.getTime() + SESSION_TTL_SECONDS * 1000,
    ).toISOString(),
  };
  const stored = await internalJson<SessionRecord>(
    accounts(env).fetch(
      internalRequest("/sessions/create", {
        sessionId: session.id,
        accountId: session.accountId,
        nickname: session.nickname,
        tokenHash: session.tokenHash,
        createdAt: session.createdAt,
        lastSeenAt: session.lastSeenAt,
        currentRoomId: session.currentRoomId,
        expiresAt: session.expiresAt,
      }),
    ),
    201,
  );
  return json(publicSession(stored), 201, {
    "set-cookie": sessionCookie(token, request.url, SESSION_TTL_SECONDS),
  });
}

async function upgradeAccount(
  request: Request,
  env: WorkerEnv,
): Promise<Response> {
  const token = requireToken(request);
  const session = await authenticate(request, env);
  if (session.accountId) throw new DomainError("INVALID_STATE");
  const body = await bodyObject(request);
  const handle = requireString(body.handle).trim();
  if (!/^[\p{L}\p{N}_-]{2,16}$/u.test(handle))
    throw new DomainError("INVALID_NICKNAME");
  const recoveryKey = randomSecret();
  const nextToken = randomSecret();
  const result = await internalJson<{
    account: PlayerAccount;
    session: SessionRecord;
  }>(
    accounts(env).fetch(
      internalRequest("/accounts/upgrade", {
        tokenHash: await sha256(token),
        nextTokenHash: await sha256(nextToken),
        handle,
        accountId: crypto.randomUUID(),
        recoveryKeyHash: await sha256(recoveryKey),
        now: new Date().toISOString(),
      }),
    ),
  );
  await internalJson(
    progression(env).fetch(
      internalRequest("/identities/migrate", {
        sourceId: session.id,
        accountId: result.account.id,
        handle: result.account.handle,
      }),
    ),
    204,
  );
  return json(
    {
      account: {
        id: result.account.id,
        handle: result.account.handle,
        createdAt: result.account.createdAt,
      },
      recoveryKey,
    },
    200,
    {
      "set-cookie": sessionCookie(nextToken, request.url, SESSION_TTL_SECONDS),
    },
  );
}

async function loginAccount(
  request: Request,
  env: WorkerEnv,
): Promise<Response> {
  const body = await bodyObject(request);
  const now = new Date();
  const token = randomSecret();
  const session = await internalJson<SessionRecord>(
    accounts(env).fetch(
      internalRequest("/accounts/login", {
        accountId: requireUuid(body.accountId),
        recoveryKeyHash: await sha256(requireString(body.recoveryKey)),
        sessionId: crypto.randomUUID(),
        nickname: "account",
        tokenHash: await sha256(token),
        createdAt: now.toISOString(),
        lastSeenAt: now.toISOString(),
        currentRoomId: null,
        expiresAt: new Date(
          now.getTime() + SESSION_TTL_SECONDS * 1000,
        ).toISOString(),
      }),
    ),
    201,
  );
  return json(publicSession(session), 201, {
    "set-cookie": sessionCookie(token, request.url, SESSION_TTL_SECONDS),
  });
}

async function createRoomRoute(
  request: Request,
  env: WorkerEnv,
): Promise<Response> {
  const token = requireToken(request);
  const session = await authenticate(request, env);
  if (session.currentRoomId) throw new DomainError("ALREADY_JOINED");
  const body = await bodyObject(request);
  const roomId = crypto.randomUUID();
  let code = "";
  let result: { snapshot: unknown } | null = null;
  for (let attempt = 0; attempt < 5 && !result; attempt += 1) {
    code = inviteCode();
    try {
      result = await internalJson<{ snapshot: unknown }>(
        room(env, roomId).fetch(
          internalRequest("/create", {
            roomId,
            code,
            name: requireString(body.name),
            visibility: body.visibility,
            rules: body.rules,
            session,
            playerId: crypto.randomUUID(),
            now: new Date().toISOString(),
          }),
        ),
        201,
      );
    } catch (error) {
      if (!(error instanceof DomainError) || error.code !== "INVALID_STATE")
        throw error;
    }
  }
  if (!result) throw new DomainError("INTERNAL_ERROR");
  await updateSessionRoom(env, token, roomId);
  return json(
    {
      snapshot: result.snapshot,
      inviteUrl: new URL(`/join/${code}`, request.url).href,
    },
    201,
  );
}

async function createPracticeRoute(
  request: Request,
  env: WorkerEnv,
): Promise<Response> {
  const token = requireToken(request);
  const session = await authenticate(request, env);
  if (session.currentRoomId) throw new DomainError("ALREADY_JOINED");
  const body = await bodyObject(request);
  const difficulty = requireString(body.difficulty);
  if (!["RECRUIT", "OFFICER", "ADMIRAL"].includes(difficulty))
    throw new DomainError("INVALID_REQUEST");
  const roomId = crypto.randomUUID();
  const now = new Date();
  const aiSession: SessionRecord = {
    id: crypto.randomUUID(),
    accountId: null,
    nickname: `MK-AI ${difficulty}`,
    tokenHash: await sha256(randomSecret()),
    createdAt: now.toISOString(),
    lastSeenAt: now.toISOString(),
    currentRoomId: roomId,
    expiresAt: new Date(
      now.getTime() + SESSION_TTL_SECONDS * 1_000,
    ).toISOString(),
  };
  let snapshot: unknown | null = null;
  for (let attempt = 0; attempt < 5 && !snapshot; attempt += 1) {
    try {
      const result = await internalJson<{ snapshot: unknown }>(
        room(env, roomId).fetch(
          internalRequest("/create-practice", {
            roomId,
            code: inviteCode(),
            difficulty,
            session,
            playerId: crypto.randomUUID(),
            aiSession,
            aiPlayerId: crypto.randomUUID(),
            now: now.toISOString(),
          }),
        ),
        201,
      );
      snapshot = result.snapshot;
    } catch (error) {
      if (!(error instanceof DomainError) || error.code !== "INVALID_STATE")
        throw error;
    }
  }
  if (!snapshot) throw new DomainError("INTERNAL_ERROR");
  await updateSessionRoom(env, token, roomId);
  return json(snapshot, 201);
}

async function joinRoomRoute(
  request: Request,
  env: WorkerEnv,
): Promise<Response> {
  const token = requireToken(request);
  const session = await authenticate(request, env);
  if (session.currentRoomId) throw new DomainError("ALREADY_JOINED");
  const body = await bodyObject(request);
  const lookup = await internalJson<{ roomId: string }>(
    lobby(env).fetch(
      internalRequest("/rooms/lookup", { code: requireString(body.code) }),
    ),
  );
  const result = await internalJson<{ snapshot: unknown }>(
    room(env, lookup.roomId).fetch(
      internalRequest("/join", {
        session,
        playerId: crypto.randomUUID(),
        now: new Date().toISOString(),
      }),
    ),
  );
  await updateSessionRoom(env, token, lookup.roomId);
  return json(result.snapshot);
}

async function enqueueMatchmaking(
  request: Request,
  env: WorkerEnv,
  ranked: boolean,
): Promise<Response> {
  const session = await authenticate(request, env);
  const now = new Date().toISOString();
  let input: Record<string, unknown>;
  if (ranked) {
    if (!session.accountId) throw new DomainError("RANKED_ACCOUNT_REQUIRED");
    const body = await bodyObject(request);
    if (
      Object.keys(body).some(
        (key) => !["pool", "region", "latencyMs"].includes(key),
      ) ||
      body.pool !== "RANKED"
    ) {
      throw new DomainError("INVALID_REQUEST");
    }
    const region = requireString(body.region);
    const latencyMs = Number(body.latencyMs);
    if (
      ![
        "KOREA",
        "JAPAN",
        "SOUTHEAST_ASIA",
        "NORTH_AMERICA_WEST",
        "NORTH_AMERICA_EAST",
        "EUROPE",
      ].includes(region) ||
      !Number.isInteger(latencyMs) ||
      latencyMs < 1 ||
      latencyMs > 300
    ) {
      throw new DomainError("INVALID_REQUEST");
    }
    const liveContent = await liveContentRuntime(env, now);
    if (liveContent.view.season.status !== "ACTIVE")
      throw new DomainError("INVALID_STATE");
    const profile = await internalJson<{ rating: number }>(
      progression(env).fetch(
        internalRequest("/ranked/profile", {
          accountId: session.accountId,
          handle: session.nickname,
          seasonId: liveContent.view.season.id,
          seasonStartsAt: liveContent.view.season.startsAt,
          now,
        }),
      ),
    );
    input = {
      session,
      pool: "RANKED",
      region,
      latencyMs,
      rating: profile.rating,
      seasonId: liveContent.view.season.id,
      contentRevision: liveContent.view.revision,
      now,
    };
  } else {
    const text = await request.text();
    if (text.length) throw new DomainError("INVALID_REQUEST");
    input = {
      session,
      pool: "CASUAL",
      region: "AUTO",
      latencyMs: 0,
      rating: null,
      seasonId: null,
      contentRevision: null,
      now,
    };
  }
  if (session.currentRoomId) {
    const snapshot = await internalJson(
      room(env, session.currentRoomId).fetch(
        internalRequest("/snapshot", { sessionId: session.id, now }),
      ),
    );
    return json({
      queued: false,
      queuedAt: null,
      ticket: {
        pool: input.pool,
        region: input.region,
        reportedLatencyMs: input.latencyMs,
        rating: input.rating,
        partySize: 1,
        searchWindow: {
          phase: "EXACT",
          ratingDelta: 100,
          maxLatencyMs: 120,
          elapsedSeconds: 0,
        },
      },
      matchQuality: null,
      snapshot,
    });
  }
  return json(
    await internalJson(
      matchmaking(env).fetch(internalRequest("/enqueue", input)),
    ),
  );
}

async function applySocialAction(
  request: Request,
  env: WorkerEnv,
): Promise<Response> {
  const session = await authenticate(request, env);
  if (!session.accountId) throw new DomainError("SOCIAL_ACCOUNT_REQUIRED");
  const body = await bodyObject(request);
  const action = requireString(body.action);
  const allowed = [
    "FRIEND_REQUEST",
    "FRIEND_RESPOND",
    "FRIEND_REMOVE",
    "PARTY_INVITE",
    "PARTY_RESPOND",
    "PARTY_LEAVE",
    "GAME_INVITE",
    "GAME_INVITE_RESPOND",
  ];
  if (!allowed.includes(action)) throw new DomainError("INVALID_REQUEST");
  let roomInfo: unknown = undefined;
  if (action === "GAME_INVITE") {
    const roomId = requireUuid(body.roomId);
    roomInfo = await internalJson(
      room(env, roomId).fetch(
        internalRequest("/invite-info", { sessionId: session.id }),
      ),
    );
  }
  return json(
    await internalJson(
      social(env).fetch(
        internalRequest("/actions", {
          ...body,
          actorId: session.accountId,
          actorHandle: session.nickname,
          roomInfo,
          now: new Date().toISOString(),
        }),
      ),
    ),
  );
}

async function updateSocialRelationship(
  request: Request,
  env: WorkerEnv,
): Promise<Response> {
  const session = await authenticate(request, env);
  const body = await bodyObject(request);
  const roomId = requireUuid(body.roomId);
  if (typeof body.muted !== "boolean" || typeof body.blocked !== "boolean")
    throw new DomainError("INVALID_REQUEST");
  const context = await internalJson<{
    actor: { sessionId: string; accountId: string | null; nickname: string };
    target: { sessionId: string; accountId: string | null; nickname: string };
  }>(
    room(env, roomId).fetch(
      internalRequest("/safety-context", {
        sessionId: session.id,
        targetPlayerId: requireUuid(body.targetPlayerId),
      }),
    ),
  );
  const identities = await internalJson<{
    identities: Array<{
      sessionId: string;
      accountId: string | null;
      nickname: string;
    }>;
  }>(
    accounts(env).fetch(
      internalRequest("/sessions/identities", {
        sessionIds: [context.actor.sessionId, context.target.sessionId],
      }),
    ),
  );
  const actorIdentity = identities.identities.find(
    (identity) => identity.sessionId === context.actor.sessionId,
  );
  const targetIdentity = identities.identities.find(
    (identity) => identity.sessionId === context.target.sessionId,
  );
  return json(
    await internalJson(
      social(env).fetch(
        internalRequest("/relationship", {
          actorIdentityId:
            actorIdentity?.accountId ??
            context.actor.accountId ??
            context.actor.sessionId,
          targetIdentityId:
            targetIdentity?.accountId ??
            context.target.accountId ??
            context.target.sessionId,
          actorNickname: actorIdentity?.nickname ?? context.actor.nickname,
          targetNickname: targetIdentity?.nickname ?? context.target.nickname,
          muted: body.muted,
          blocked: body.blocked,
          now: new Date().toISOString(),
        }),
      ),
    ),
  );
}

async function reportPlayer(
  request: Request,
  env: WorkerEnv,
): Promise<Response> {
  const session = await authenticate(request, env);
  const body = await bodyObject(request);
  const roomId = requireUuid(body.roomId);
  const context = await internalJson<{
    roomVersion: number;
    roomState: string;
    actor: { sessionId: string; accountId: string | null; nickname: string };
    target: {
      playerId: string;
      sessionId: string;
      accountId: string | null;
      nickname: string;
    };
    messages: unknown[];
    recentAttacks: unknown[];
  }>(
    room(env, roomId).fetch(
      internalRequest("/safety-context", {
        sessionId: session.id,
        targetPlayerId: requireUuid(body.targetPlayerId),
      }),
    ),
  );
  const identities = await internalJson<{
    identities: Array<{
      sessionId: string;
      accountId: string | null;
      nickname: string;
    }>;
  }>(
    accounts(env).fetch(
      internalRequest("/sessions/identities", {
        sessionIds: [context.actor.sessionId, context.target.sessionId],
      }),
    ),
  );
  const reporter = identities.identities.find(
    (identity) => identity.sessionId === context.actor.sessionId,
  );
  const target = identities.identities.find(
    (identity) => identity.sessionId === context.target.sessionId,
  );
  const now = new Date().toISOString();
  const receipt = await internalJson(
    operations(env).fetch(
      internalRequest("/reports/create", {
        reporterIdentityId:
          reporter?.accountId ??
          context.actor.accountId ??
          context.actor.sessionId,
        targetIdentityId:
          target?.accountId ??
          context.target.accountId ??
          context.target.sessionId,
        roomId,
        targetPlayerId: context.target.playerId,
        targetNickname: target?.nickname ?? context.target.nickname,
        category: body.category,
        details: body.details,
        evidence: {
          protocolVersion: PROTOCOL_VERSION,
          roomId,
          roomVersion: context.roomVersion,
          roomState: context.roomState,
          reportedPlayerId: context.target.playerId,
          reportedNickname: target?.nickname ?? context.target.nickname,
          messages: context.messages,
          recentAttacks: context.recentAttacks,
          capturedAt: now,
        },
        now,
      }),
    ),
    201,
  );
  return json({ report: receipt }, 201);
}

async function moderateReport(
  request: Request,
  env: WorkerEnv,
  reportId: string,
): Promise<Response> {
  const operatorId = authorizeOperator(request, env, true);
  const body = await bodyObject(request);
  const result = await internalJson<{
    action: { targetIdentityId: string; action: string };
  }>(
    operations(env).fetch(
      internalRequest("/reports/moderate", {
        reportId,
        operatorId,
        action: body.action,
        reason: body.reason,
        durationHours: body.durationHours ?? null,
        reversesActionId: body.reversesActionId ?? null,
        now: new Date().toISOString(),
      }),
    ),
  );
  if (["SUSPEND", "BAN"].includes(result.action.action)) {
    const revoked = await internalJson<{
      revoked: RevokedSession[];
    }>(
      accounts(env).fetch(
        internalRequest("/moderation/revoke", {
          identityId: result.action.targetIdentityId,
        }),
      ),
    );
    await Promise.all(
      revoked.revoked.map((session) => disconnectRevokedSession(env, session)),
    );
  }
  return json(result);
}

async function supportAccount(
  env: WorkerEnv,
  query: string | null,
): Promise<Response> {
  if (!query) throw new DomainError("INVALID_REQUEST");
  const normalized = query.trim();
  if (
    [...normalized].length < 3 ||
    [...normalized].length > 64 ||
    [...normalized].some((character) => /[\u0000-\u001f\u007f]/.test(character))
  ) {
    throw new DomainError("INVALID_REQUEST");
  }
  const core = await internalJson<{
    account: PlayerAccount;
    sessions: unknown[];
  }>(
    accounts(env).fetch(
      internalRequest("/support/find", { query: normalized }),
    ),
  );
  const audit = await internalJson<{ actions: unknown[] }>(
    operations(env).fetch(
      internalRequest("/support/actions", { accountId: core.account.id }),
    ),
  );
  return json({ ...core, actions: audit.actions });
}

async function revokeSupportSessions(
  request: Request,
  env: WorkerEnv,
  accountId: string,
): Promise<Response> {
  const operatorId = authorizeOperator(request, env, true);
  const body = await bodyObject(request);
  const reason = requireString(body.reason).trim();
  if ([...reason].length < 8 || [...reason].length > 500)
    throw new DomainError("INVALID_REQUEST");
  const sessionId =
    body.sessionId === undefined || body.sessionId === null
      ? null
      : requireUuid(body.sessionId);
  const revoked = await internalJson<{ revoked: RevokedSession[] }>(
    accounts(env).fetch(
      internalRequest("/support/revoke", { accountId, sessionId }),
    ),
  );
  const result = await internalJson(
    operations(env).fetch(
      internalRequest("/support/record", {
        accountId,
        operatorId,
        reason,
        targetSessionId: sessionId,
        affectedSessionIds: revoked.revoked.map((session) => session.sessionId),
        now: new Date().toISOString(),
      }),
    ),
  );
  await Promise.all(
    revoked.revoked.map((session) => disconnectRevokedSession(env, session)),
  );
  return json(result);
}

async function mutateLiveContent(
  request: Request,
  env: WorkerEnv,
  operation: "/validate" | "/publish" | "/rollback",
  status: 200 | 201,
): Promise<Response> {
  const operatorId = authorizeOperator(request, env, true);
  const body = await bodyObject(request);
  const result = await internalJson(
    content(env).fetch(
      internalRequest(operation, {
        ...body,
        operatorId,
        now: new Date().toISOString(),
      }),
    ),
    status,
  );
  return json(result, status);
}

async function websocket(request: Request, env: WorkerEnv): Promise<Response> {
  try {
    if (request.headers.get("upgrade")?.toLowerCase() !== "websocket") {
      return json({ code: "UPGRADE_REQUIRED" }, 426);
    }
    const url = new URL(request.url);
    await enforceRateLimit(request, env, "websocket", 60, 60_000);
    const origin = request.headers.get("origin");
    if (origin && origin !== url.origin) throw new DomainError("UNAUTHORIZED");
    const session = await authenticate(request, env);
    if (!session.currentRoomId) throw new DomainError("NOT_ROOM_MEMBER");
    const headers = new Headers(request.headers);
    headers.set("x-mk01-session-id", session.id);
    return room(env, session.currentRoomId).fetch(
      new Request("https://internal.mk01/websocket", {
        method: "GET",
        headers,
      }),
    );
  } catch (error) {
    return errorResponse(error);
  }
}

async function enforceHttpRateLimits(
  request: Request,
  env: WorkerEnv,
): Promise<void> {
  const pathname = new URL(request.url).pathname;
  const checks = [enforceRateLimit(request, env, "http-ip", 600, 60_000)];
  const token = cookieValue(request);
  if (token)
    checks.push(
      enforceRateLimit(request, env, "http-session", 240, 60_000, token),
    );
  if (request.method === "POST" && pathname === "/api/sessions") {
    checks.push(enforceRateLimit(request, env, "session-create", 20, 60_000));
  }
  await Promise.all(checks);
}

async function enforceRateLimit(
  request: Request,
  env: WorkerEnv,
  category: string,
  limit: number,
  windowMs: number,
  identity?: string,
): Promise<void> {
  const client =
    identity ??
    request.headers.get("cf-connecting-ip") ??
    request.headers.get("x-real-ip") ??
    "local-client";
  const key = await sha256(`${category}:${client}`);
  const limiter = env.RATE_LIMITS.get(env.RATE_LIMITS.idFromName(key));
  await internalJson(
    limiter.fetch(
      internalRequest("/check", { limit, windowMs, now: Date.now() }),
    ),
    204,
  );
}

async function authenticate(
  request: Request,
  env: WorkerEnv,
): Promise<SessionRecord> {
  const token = requireToken(request);
  return internalJson<SessionRecord>(
    accounts(env).fetch(
      internalRequest("/sessions/authenticate", {
        tokenHash: await sha256(token),
        now: new Date().toISOString(),
      }),
    ),
  );
}

async function updateSessionRoom(
  env: WorkerEnv,
  token: string,
  roomId: string | null,
): Promise<void> {
  await internalJson(
    accounts(env).fetch(
      internalRequest("/sessions/room", {
        tokenHash: await sha256(token),
        roomId,
      }),
    ),
    204,
  );
}

interface RevokedSession {
  sessionId: string;
  roomId: string | null;
}

async function disconnectRevokedSession(
  env: WorkerEnv,
  revoked: RevokedSession,
): Promise<void> {
  await internalJson(
    matchmaking(env).fetch(
      internalRequest("/cancel", { sessionId: revoked.sessionId }),
    ),
    204,
  );
  if (!revoked.roomId) return;
  await internalJson(
    room(env, revoked.roomId).fetch(
      internalRequest("/disconnect-session", {
        sessionId: revoked.sessionId,
        now: new Date().toISOString(),
      }),
    ),
    204,
  );
}

async function proxyRoomSnapshot(
  env: WorkerEnv,
  roomId: string,
  session: SessionRecord,
): Promise<Response> {
  return json(
    await internalJson(
      room(env, roomId).fetch(
        internalRequest("/snapshot", {
          sessionId: session.id,
          now: new Date().toISOString(),
        }),
      ),
    ),
  );
}

function acceptsProtocol(request: Request): boolean {
  const value = request.headers.get("x-mk01-protocol-version");
  if (value === null) return true;
  const version = Number(value);
  return (
    Number.isInteger(version) &&
    version >= MIN_PROTOCOL_VERSION &&
    version <= MAX_PROTOCOL_VERSION
  );
}

function requireToken(request: Request): string {
  const token = cookieValue(request);
  if (!token) throw new DomainError("UNAUTHORIZED");
  return token;
}

function accounts(env: WorkerEnv) {
  return env.ACCOUNTS.get(env.ACCOUNTS.idFromName(GLOBAL_OBJECT_ID));
}

function lobby(env: WorkerEnv) {
  return env.LOBBY.get(env.LOBBY.idFromName(GLOBAL_OBJECT_ID));
}

function room(env: WorkerEnv, roomId: string) {
  return env.GAME_ROOMS.get(env.GAME_ROOMS.idFromName(roomId));
}

function progression(env: WorkerEnv) {
  return env.PROGRESSION.get(env.PROGRESSION.idFromName(GLOBAL_OBJECT_ID));
}

function matchmaking(env: WorkerEnv) {
  return env.MATCHMAKING.get(env.MATCHMAKING.idFromName(GLOBAL_OBJECT_ID));
}

function social(env: WorkerEnv) {
  return env.SOCIAL.get(env.SOCIAL.idFromName(GLOBAL_OBJECT_ID));
}

function operations(env: WorkerEnv) {
  return env.OPERATIONS.get(env.OPERATIONS.idFromName(GLOBAL_OBJECT_ID));
}

function content(env: WorkerEnv) {
  return env.CONTENT.get(env.CONTENT.idFromName(GLOBAL_OBJECT_ID));
}

async function liveContentRuntime(env: WorkerEnv, now: string) {
  return internalJson<{
    view: {
      revision: number;
      season: { id: string; startsAt: string; endsAt: string; status: string };
      featureFlags: { missionsEnabled: boolean; eventBannerEnabled: boolean };
      [key: string]: unknown;
    };
    tuning: {
      dailyDeploymentRewardXp: number;
      dailyAccuracyRewardXp: number;
      weeklySupremacyRewardXp: number;
    };
  }>(content(env).fetch(internalRequest("/runtime", { now })));
}

function authorizeOperator(
  request: Request,
  env: WorkerEnv,
  requireOperatorId: boolean,
): string {
  const supplied = request.headers
    .get("authorization")
    ?.match(/^Bearer (.+)$/)?.[1];
  const expected = env.ADMIN_TOKEN;
  if (
    !supplied ||
    !expected ||
    expected.length < 32 ||
    !constantTimeTextEqual(supplied, expected)
  ) {
    throw new DomainError("UNAUTHORIZED");
  }
  const operatorId = request.headers.get("x-operator-id")?.trim() ?? "";
  if (requireOperatorId && !operatorId)
    throw new DomainError("INVALID_REQUEST");
  return operatorId;
}

function constantTimeTextEqual(left: string, right: string): boolean {
  const length = Math.max(left.length, right.length);
  let difference = left.length ^ right.length;
  for (let index = 0; index < length; index += 1) {
    difference |=
      (left.charCodeAt(index) || 0) ^ (right.charCodeAt(index) || 0);
  }
  return difference === 0;
}

async function internalJson<T = unknown>(
  responsePromise: Promise<Response>,
  expectedStatus = 200,
): Promise<T> {
  const response = await responsePromise;
  if (response.status !== expectedStatus) {
    const payload = (await response.json().catch(() => null)) as {
      code?: string;
    } | null;
    if (payload?.code) throw new DomainError(payload.code as ErrorCode);
    throw new DomainError("INTERNAL_ERROR");
  }
  if (response.status === 204) return undefined as T;
  return (await response.json()) as T;
}

function inviteCode(): string {
  const alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  const bytes = crypto.getRandomValues(new Uint8Array(6));
  return [...bytes].map((byte) => alphabet[byte % alphabet.length]).join("");
}
