apiVersion: 1

datasources:
  - name: Mk.01 Prometheus
    uid: mk01-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.53.0
      timeInterval: 30s
